### ISSUE TITLE
Naming rules

### ISSUE THREAD

**Issue by PascalIrz** [agistaterre/mov-around#3]
Suggestions:

- functions' names start with verbs
- all names are in English
- no uppercase
- the word separator in names is the underscore "_"
- a dictionary to accurately define the objects (eg clarify what is a `segment `vs. a `sensor name` vs. a `sensor ID`)

**Comment by timlegrand** [comment]
Approved ! :)

Only few details:

1. By dictionary do you mean glossary ?

2. This naming convention is called "snake_case" (main naming convention in Python).
> - no uppercase
> - the word separator in names is the underscore "_"

3. Would you create a MR on the `CONTRIBUTING.md` file to endorse this proposal ?

**Comment by PascalIrz** [comment]
Ok for the glossary.
Another suggestion would be to stick to meaningful names, eg avoid `variable1`, `box1`, etc. ?
Maybe the original writing is more understandable for non-pro developpers than refering to the "snake_case" naming convention.
I propose a PR.
